#provide both anchored and unachored commands via 'over'
<user.format_text>$: insert(format_text)
<user.format_text> over: insert(format_text)
phrase <user.text>$: insert(text)
phrase <user.text> over: insert(text)
(say | speak) <user.text>$: insert(text)
(say | speak) <user.text> over: insert(text)
word <user.text>: insert(text)
list formatters: user.list_formatters()
hide formatters: user.hide_formatters()